const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const webpack = require('webpack');

// // 
// new webpack.ProvidePlugin({
//   paypalCheckout: 'https://www.paypalobjects.com/api/checkout.js',
//   // ...
// });

/**
 * NOTE:
 * -----
 * server is started with https://github.com/webpack/webpack-dev-server
 */

module.exports = {
  mode: 'development',
  entry: './src/index.js',
  output: {
    filename: 'bundle.js',
    path: path.join(__dirname, 'dist'),
    publicPath: '/', // fixes the "Cannot GET /link" problem
  },
  devServer: {
    historyApiFallback: true,
  },
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          'style-loader', // Help webpack to collect CSS from all the css files referenced in your application and put it into a string
          'css-loader' // Take the output string generated by the above css-loader and put it inside the <style> tags in the index.html file
        ],
      },
      {
        test: /\.(png|jpg|gif|mp3)$/,
        use: [
          {
            loader: 'file-loader',
            options: {}
          }
        ]
      },
      {
        // For every JavaScript file
        test: /\.js$/,
        exclude: /(node_modules)/,  // except the one in "node_modules"
        use: {
          loader: 'babel-loader', // use the following loaders
          options: { // Activate the following options
            presets: [
              '@babel/preset-env', // babel environment
              '@babel/preset-react' // react conversion (JSX, ...)
            ]
          }
        }
      }
    ]
  }, // module
  plugins: [
    new HtmlWebpackPlugin({
      title: '---My App',
      filename: 'index.html',
      template: './src/index.html'
    })
  ],
  node: { // fixes "Can't resolve 'fs' when bundle with webpack" error message
    fs: 'empty'
  }
}